import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import "./globals.css";
import "@radix-ui/themes/styles.css";

import SessionProviders from "@/components/SessionProviders";
import MainNav from "@/components/MainNav";          // ⬅️ nuevo

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviders>
          <Theme>
            {/* --- Cabecera con la navegación --- */}
            <header className="p-4 border-b">
              <MainNav />
            </header>

            {/* --- Contenido de cada página --- */}
            <main className="p-6">{children}</main>
          </Theme>
        </SessionProviders>
      </body>
    </html>
  );
}
